import Vue from 'vue';
import { Ripple, Intersect } from 'vuetify/lib/directives';
import Vuetify, {
  VAlert,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAutocomplete,
  VBadge,
  VBtn,
  VBtnToggle,
  VCalendar,
  VCard,
  VCardActions,
  VCardSubtitle,
  VCardText,
  VCardTitle,
  VCarousel,
  VCarouselItem,
  VCheckbox,
  VChip,
  VCol,
  VCombobox,
  VContainer,
  VDataTable,
  VDatePicker,
  VDialog,
  VDivider,
  VExpansionPanel,
  VExpansionPanelContent,
  VExpansionPanelHeader,
  VExpansionPanels,
  VFooter,
  VForm,
  VIcon,
  VImg,
  VLazy,
  VList,
  VListGroup,
  VListItem,
  VListItemAction,
  VListItemContent,
  VListItemIcon,
  VListItemTitle,
  VMain,
  VMenu,
  VNavigationDrawer,
  VOverlay,
  VProgressCircular,
  VRadio,
  VRadioGroup,
  VRow,
  VSelect,
  VSimpleTable,
  VSkeletonLoader,
  VSnackbar,
  VSpacer,
  VSpeedDial,
  VSubheader,
  VSwitch,
  VTab,
  VTabs,
  VTextarea,
  VTextField,
  VToolbar,
  VToolbarTitle,
  VTooltip
} from 'vuetify/lib';
import ja from 'vuetify/src/locale/ja';

Vue.use(Vuetify, {
  components: {
    VAlert,
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAutocomplete,
    VBadge,
    VBtn,
    VBtnToggle,
    VCalendar,
    VCard,
    VCardActions,
    VCardSubtitle,
    VCardText,
    VCardTitle,
    VCarousel,
    VCarouselItem,
    VCheckbox,
    VChip,
    VCol,
    VCombobox,
    VContainer,
    VDataTable,
    VDatePicker,
    VDialog,
    VDivider,
    VExpansionPanel,
    VExpansionPanelContent,
    VExpansionPanelHeader,
    VExpansionPanels,
    VFooter,
    VForm,
    VIcon,
    VImg,
    VLazy,
    VList,
    VListGroup,
    VListItem,
    VListItemAction,
    VListItemContent,
    VListItemIcon,
    VListItemTitle,
    VMain,
    VMenu,
    VNavigationDrawer,
    VOverlay,
    VProgressCircular,
    VRadio,
    VRadioGroup,
    VRow,
    VSelect,
    VSimpleTable,
    VSkeletonLoader,
    VSnackbar,
    VSpacer,
    VSpeedDial,
    VSubheader,
    VSwitch,
    VTab,
    VTabs,
    VTextarea,
    VTextField,
    VToolbar,
    VToolbarTitle,
    VTooltip
  },
  directives: {
    Ripple,
    Intersect
  }
});

const lightThemeSettings = {
  primary: '#1F76DD',
  secondary: '#EDC32F',
  accent: '#04E3EC',
  neutral: '#113364',
  neutral_light: '#F3F7FB',
  error: '#FF5252',
  info: '#2196F3',
  success: '#4CAF50',
  warning: '#FB8C00'
};

export type VFormObj = Vue & { validate(): boolean };

export default new Vuetify({
  lang: {
    locales: { ja },
    current: 'ja'
  },
  theme: {
    dark: false,
    themes: {
      light: lightThemeSettings
    }
  },
  icons: {
    iconfont: 'mdi'
  }
});
